-- Populate the default schools table so the "Default 2026 Set" option
-- in create-auction has data to copy into auction_schools.
-- Uses ON CONFLICT DO NOTHING so re-running is safe.

INSERT INTO schools (name, logo_url) VALUES
  -- SEC
  ('Alabama',         'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png'),
  ('Auburn',          'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png'),
  ('Georgia',         'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png'),
  ('Florida',         'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png'),
  ('Tennessee',       'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png'),
  ('LSU',             'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png'),
  ('Texas A&M',       'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png'),
  ('Ole Miss',        'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png'),
  ('Mississippi State','https://a.espncdn.com/i/teamlogos/ncaa/500/344.png'),
  ('Arkansas',        'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png'),
  ('Kentucky',        'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png'),
  ('Missouri',        'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png'),
  ('South Carolina',  'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png'),
  ('Vanderbilt',      'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png'),
  -- Big Ten
  ('Ohio State',      'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png'),
  ('Michigan',        'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png'),
  ('Penn State',      'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png'),
  ('Wisconsin',       'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png'),
  ('Iowa',            'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png'),
  ('Minnesota',       'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png'),
  ('Illinois',        'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png'),
  ('Northwestern',    'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png'),
  ('Indiana',         'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png'),
  ('Purdue',          'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png'),
  ('Rutgers',         'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png'),
  ('Maryland',        'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png'),
  ('Nebraska',        'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png'),
  ('Michigan State',  'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png'),
  -- ACC
  ('Clemson',         'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png'),
  ('Florida State',   'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png'),
  ('Miami',           'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png'),
  ('North Carolina',  'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png'),
  ('NC State',        'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png'),
  ('Virginia',        'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png'),
  ('Virginia Tech',   'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png'),
  ('Georgia Tech',    'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png'),
  ('Pittsburgh',      'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png'),
  ('Boston College',  'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png'),
  ('Wake Forest',     'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png'),
  ('Duke',            'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png'),
  ('Syracuse',        'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png'),
  ('Louisville',      'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png'),
  ('Notre Dame',      'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png'),
  -- Big 12
  ('Texas',           'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png'),
  ('Oklahoma',        'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png'),
  ('Texas Tech',      'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png'),
  ('TCU',             'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png'),
  ('Baylor',          'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png'),
  ('Kansas State',    'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png'),
  ('Kansas',          'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png'),
  ('Iowa State',      'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png'),
  ('Oklahoma State',  'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png'),
  ('West Virginia',   'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png'),
  ('UCF',             'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png'),
  ('BYU',             'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png'),
  ('Cincinnati',      'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png'),
  ('Houston',         'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png'),
  -- Flex / Independent / Other Power programs
  ('Oregon',          'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png'),
  ('USC',             'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png'),
  ('UCLA',            'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png'),
  ('Washington',      'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png'),
  ('Utah',            'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png'),
  ('Arizona State',   'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png'),
  ('Arizona',         'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png'),
  ('Colorado',        'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png')
ON CONFLICT (name) DO NOTHING;
